apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilis-app
  labels:
    app: agilis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agilis-app
  template:
    metadata:
      labels:
        app: agilis-app
    spec:
      containers:
        - name: agilis-app
          image: smokeeaasd/agilis-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:30080"