apiVersion: v1
kind: Service
metadata:
  name: agilis-app
spec:
  selector:
    app: agilis-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30081
  type: NodePort
